import os
import rtconfig
from building import *


cwd = GetCurrentDir()

# add general drivers
src = Split('''
board.c
drv_usart.c
''')


path =  [cwd]


# STM32F100xB || STM32F100xE || STM32F101x6
# STM32F101xB || STM32F101xE || STM32F101xG
# STM32F102x6 || STM32F102xB || STM32F103x6
# STM32F103xB || STM32F103xE || STM32F103xG
# STM32F105xC || STM32F107xC)
# You can select chips from the list above
CPPDEFINES = ['USE_STDPERIPH_DRIVER','STM32F10X_CL']
group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)
Return('group')
